// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLfhwgLvn0TsxMaJYkCe21SfFRlBHiFk',
    appId: '1:823512595658:web:a97b1e871e175326e1c833',
    messagingSenderId: '823512595658',
    projectId: 'risky-pets-8be2e',
    authDomain: 'risky-pets-8be2e.firebaseapp.com',
    storageBucket: 'risky-pets-8be2e.firebasestorage.app',
    measurementId: 'G-CHSM0NPHFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0F5SIDOW1sVl5gPshCVQAO6mwF8QzZmQ',
    appId: '1:823512595658:android:c55f1bbfe4d98da8e1c833',
    messagingSenderId: '823512595658',
    projectId: 'risky-pets-8be2e',
    storageBucket: 'risky-pets-8be2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKM-q8M8ESM5iPDd9J3FXemyFM5NHqqhA',
    appId: '1:823512595658:ios:66111559c3edfc0ce1c833',
    messagingSenderId: '823512595658',
    projectId: 'risky-pets-8be2e',
    storageBucket: 'risky-pets-8be2e.firebasestorage.app',
    iosClientId: '823512595658-7m8ses9r3h0l7pmuji06gvk0leu69ha2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKM-q8M8ESM5iPDd9J3FXemyFM5NHqqhA',
    appId: '1:823512595658:ios:66111559c3edfc0ce1c833',
    messagingSenderId: '823512595658',
    projectId: 'risky-pets-8be2e',
    storageBucket: 'risky-pets-8be2e.firebasestorage.app',
    iosClientId: '823512595658-7m8ses9r3h0l7pmuji06gvk0leu69ha2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnLfhwgLvn0TsxMaJYkCe21SfFRlBHiFk',
    appId: '1:823512595658:web:b80d32d4aebe37cae1c833',
    messagingSenderId: '823512595658',
    projectId: 'risky-pets-8be2e',
    authDomain: 'risky-pets-8be2e.firebaseapp.com',
    storageBucket: 'risky-pets-8be2e.firebasestorage.app',
    measurementId: 'G-WCHVPRLR5E',
  );
}
